export const galleryPhotos = [
  { src: "/images/ayurveda/joint-pain.jpg", w: 1600, h: 1200 },
  { src: "/images/ayurveda/joint-pain2.webp", w: 1536, h: 1536 },
  { src: "/images/ayurveda/kidney-failure.webp", w: 1440, h: 1440 },
  { src: "/images/ayurveda/panchakarma-infographic.png", w: 1536, h: 1024 },
  { src: "/images/ayurveda/panchakarma.jpg", w: 960, h: 1280 },
  { src: "/images/ayurveda/shirodhara.jpg", w: 1080, h: 1920 },
  { src: "/images/brand/logo-alt.webp", w: 1536, h: 1536 },
  { src: "/images/brand/logo.png", w: 1200, h: 600 },
  { src: "/images/corporate/speaking.jpg", w: 1600, h: 900 },
  { src: "/images/corporate/speaking2.jpg", w: 728, h: 1600 },
  { src: "/images/corporate/speaking3.jpg", w: 1255, h: 1558 },
  { src: "/images/events/dance-class.jpg", w: 900, h: 1600 },
  { src: "/images/events/group-outdoor.jpg", w: 1200, h: 1600 },
  { src: "/images/events/holi-celebration.jpg", w: 728, h: 1600 },
  { src: "/images/events/holi-women.jpg", w: 900, h: 1600 },
  { src: "/images/events/kids-dance.jpg", w: 1600, h: 900 },
  { src: "/images/events/kids-group.jpg", w: 1600, h: 1200 },
  { src: "/images/events/outdoor-meditation.jpg", w: 1600, h: 900 },
  { src: "/images/events/outdoor-seated.png", w: 1200, h: 600 },
  { src: "/images/events/outdoor-session.jpg", w: 1255, h: 1417 },
  { src: "/images/events/outdoor-session2.jpg", w: 1255, h: 1417 },
  { src: "/images/events/outdoor-walk.png", w: 1200, h: 600 },
  { src: "/images/events/outdoor-yoga.jpg", w: 1600, h: 900 },
  { src: "/images/events/weight-loss.jpg", w: 1280, h: 960 },
  { src: "/images/people/founder-alt.png", w: 1200, h: 600 },
  { src: "/images/people/founder.jpg", w: 960, h: 1280 },
  { src: "/images/people/interview.jpg", w: 1254, h: 1567 },
  { src: "/images/people/podcast.jpg", w: 1600, h: 728 },
  { src: "/images/people/portrait-beard.jpg", w: 960, h: 1280 },
  { src: "/images/people/portrait-small.jpg", w: 534, h: 374 },
  { src: "/images/products/mats-rolled.jpg", w: 554, h: 554 },
  { src: "/images/products/mats-stack.jpg", w: 638, h: 481 },
  { src: "/images/studio/certificates.jpg", w: 728, h: 1600 },
  { src: "/images/studio/group-celebration.jpg", w: 960, h: 1280 },
  { src: "/images/studio/handstand-teach.jpg", w: 728, h: 1600 },
  { src: "/images/studio/handstand-teach2.jpg", w: 1600, h: 1200 },
  { src: "/images/studio/lunge-class.jpg", w: 728, h: 1600 },
  { src: "/images/studio/lying-class-green.jpg", w: 1600, h: 1200 },
  { src: "/images/studio/props-room.jpg", w: 1213, h: 1600 },
  { src: "/images/studio/props-room2.jpg", w: 960, h: 1280 },
  { src: "/images/studio/savasana-green.jpg", w: 728, h: 1600 },
  { src: "/images/studio/team-group.jpg", w: 1600, h: 1200 },
  { src: "/images/studio/tree-pose-class.jpg", w: 554, h: 554 },
  { src: "/images/studio/tree-pose2.jpg", w: 1600, h: 1200 },
  { src: "/images/studio/warrior-class.jpg", w: 1280, h: 582 },
  { src: "/ketan.png", w: 900, h: 1600 },
  { src: "/images/studio/seated-circle.jpg", w: 1280, h: 720 },
]


export const galleryVideos = [
  { src: "/videos/celebration.mp4", poster: "/posters/celebration.jpg" },
  { src: "/videos/certificates.mp4", poster: "/posters/certificates.jpg" },
  { src: "/videos/community.mp4", poster: "/posters/community.jpg" },
  { src: "/videos/hero-class.mp4", poster: "/posters/hero-class.jpg" },
  { src: "/videos/kids-dance.mp4", poster: "/posters/kids-dance.jpg" },
  { src: "/videos/meditation.mp4", poster: "/posters/meditation.jpg" },
  { src: "/videos/outdoor-yoga.mp4", poster: "/posters/outdoor-yoga.jpg" },
  { src: "/videos/shirodhara.mp4", poster: "/posters/shirodhara.jpg" },
]